Add semver Output

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -126,6 +126,10 @@ jobs:
             echo "Invalid Output: tags"
             exit 1
           fi
+          if [ -z '${{ steps.test4.outputs.semver }}' ];then
+            echo "Invalid Output: semver"
+            exit 1
+          fi
 
       #- name: "Cleanup Tag"
       #  if: ${{ always() }}
